[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Necesario para SSR en Netlify
[functions]
  included_files = [".next/standalone/**"]
  node_bundler = "esbuild"

# Configuración para Next.js en Netlify
[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

# Reglas de redirección para autenticación
[[redirects]]
  from = "/auth/*"
  to = "/auth/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/auth/login"
  status = 301

[[redirects]]
  from = "/logout"
  to = "/auth/logout"
  status = 301

# Regla para SPA - redirige todas las rutas no encontradas al index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
